ALPACA_API_BASE_URL = "https://paper-api.alpaca.markets"

PAPER_API_ID = "PK92A2VGKAAR9WB08JLW"
PAPER_SECRET_KEY = "xjsGTIqTaQpkWKBBNGjvIiRi5Mk75W0opie4gXWU"

TICKERS = {
    "APPLE_TICKER": "AAPL",
    "MICROSOFT_TICKER": "MSFT",
    "CORNING_TICKER": "GLW",
    "NVIDIA_TICKER": "NVDA",
    "AMD_TICKER": "AMD",
    }



